// @title Pack Calculator API
// @version 1.0
// @description HTTP API to configure pack sizes and calculate how many packs to ship for an order (whole packs only; minimises items shipped, then pack count).
// @termsOfService http://swagger.io/terms/

// @contact.name API Support

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /

// @schemes http https
package main

import (
	"net/http"
	"pack-calculator/cmd/handler"
	_ "pack-calculator/docs"
	"pack-calculator/internal/utils"
	"time"

	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func main() {
	logger := utils.NewLogger()

	handler, err := handler.NewHandler(logger)
	if err != nil {
		logger.Error("error instantiating handler", "error", err)
		panic("error instantiating handler")
	}

	// add routes
	mux := http.NewServeMux()
	mux.HandleFunc("GET /pack_size/batch", handler.GetPackSizes)
	mux.HandleFunc("POST /pack_size/batch", handler.SavePackSize)
	mux.HandleFunc("POST /calculate", handler.Calculate)

	// Swagger UI and OpenAPI JSON (generated by swag).
	mux.Handle("GET /swagger/", httpSwagger.WrapHandler)
	mux.HandleFunc("GET /swagger", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/swagger/index.html", http.StatusSeeOther)
	})

	server := &http.Server{
		Addr:         ":8080",
		Handler:      mux,
		ReadTimeout:  5 * time.Second,  // TODO: needs to be changed?
		WriteTimeout: 5 * time.Second,  // TODO: needs to be changed?
		IdleTimeout:  15 * time.Second, // TODO: needs to be changed?
	}

	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		logger.Error("could not start the server, error", "error", err)
		panic("could not start the server")
	}
}
