// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculate": {
            "post": {
                "description": "Accepts the number of items ordered and returns the order including a generated event_id. Pack mix is computed according to business rules.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Calculate packs for an order",
                "parameters": [
                    {
                        "description": "Order payload (items required)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/common.Order"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Order"
                        }
                    },
                    "400": {
                        "description": "Payload in the wrong format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error calculating order",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pack_size/batch": {
            "post": {
                "description": "Clears existing sizes in the database and inserts the provided list. The sizes array must not be empty.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pack_sizes"
                ],
                "summary": "Replace pack sizes",
                "parameters": [
                    {
                        "description": "Pack sizes to use for fulfilment",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/common.PackSizeBatch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pack sizes saved",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Payload in the wrong format or no sizes passed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error saving pack sizes",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Order": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string"
                },
                "items": {
                    "type": "integer"
                },
                "packs": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        },
        "common.PackSizeBatch": {
            "type": "object",
            "properties": {
                "sizes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Pack Calculator API",
	Description:      "HTTP API to configure pack sizes and calculate how many packs to ship for an order (whole packs only; minimises items shipped, then pack count).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
